#!/bin/sh

rm -f  aclocal.m4 \
       config.h config.h.in \
       config.status config.log \
       src/Makevars \
       src/autoloads.h src/ldflags.txt src/littler.h \
       src/r src/gitversion.h *~ *.o \
       stamp-h1
rm -rf autom4te.cache .deps inst/bin/
