#!/bin/sh

rm -f  aclocal.m4 \
       config.h config.h.in \
       config.status config.log \
       Makefile Makefile.in \
       autoloads.h ldflags.txt littler.h \
       r svnversion.h *~ *.o
rm -rf autom4te.cache

