\input texinfo @c -*-texinfo-*-
@c This file uses the @command command introduced in Texinfo 4.0.
@c %**start of header
@setfilename littler.info
@settitle Provides shebang capability for R (www.r-project.org)
@finalout
@setchapternewpage odd
@c %**end of header

@set VERSION 0.1.0

@ifinfo
This file documents the @command{littler} command which Provides shebang capability for R (www.r-project.org)

Copyright (C) 2006 Jeffrey Horner and Dirk Eddelbuettel

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

@ignore
Permission is granted to process this file through TeX and print the
results, provided the printed document carries copying permission
notice identical to this one except for the removal of this paragraph
(this paragraph not being relevant to the printed manual).

@end ignore
Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by the Foundation.
@end ifinfo

@titlepage
@title littler
@subtitle Provides shebang capability for R (www.r-project.org)
@subtitle for littler Version @value{VERSION}
@author by Jeffrey Horner and Dirk Eddelbuettel

@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2006 Jeffrey Horner and Dirk Eddelbuettel

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by the Foundation.
@end titlepage

@c All the nodes can be updated using the EMACS command
@c texinfo-every-node-update, which is normally bound to C-c C-u C-e.
@node Top, Instructions, (dir), (dir)

@ifinfo
This file documents the @command{littler} command to Provides shebang capability for R (www.r-project.org).
@end ifinfo

@c All the menus can be updated with the EMACS command
@c texinfo-all-menus-update, which is normally bound to C-c C-u C-a.
@menu
* Instructions::                How to read this manual. 
* Overview::                    Preliminary information.
* Sample::                      Sample output from @command{littler}.
* Invoking littler::            How to run @command{littler}.
* Problems::                    Reporting bugs.
* Copying::                     How you can copy and share @command{littler}.
* Concept Index::               Index of concepts.
@end menu

@node Instructions, Copying, Top, Top
@chapter How to Read This Manual

@cindex reading
@cindex manual, how to read
@cindex how to read
To read this manual, begin at the beginning, reading from left to right
and top to bottom, until you get to the end.  Then stop.  You may pause
for a beer anywhere in the middle as well, if you wish.  (Please note,
however, that The King strongly advises against heavy use of
prescription pharmaceuticals, based on his extensive personal and
professional experience.)

@node Overview, Sample, Copying, Top
@chapter Overview
@cindex greetings
@cindex overview

The GNU @command{littler} program produces a familiar, friendly greeting.
It allows nonprogrammers to use a classic computer science tool which
would otherwise be unavailable to them.  Because it is protected by the
GNU General Public License, users are free to share and change it.

GNU @command{littler} was written by Jeffrey Horner and Dirk Eddelbuettel.

@node Sample, Invoking littler, Overview, Top
@chapter Sample Output
@cindex sample

Here are some realistic examples of running @command{littler}.

This is the output of the command @samp{littler}:

@example
hello, world!
@end example

This is the output of the command @samp{littler --help}:

@example

Usage: littler [options...] FILE [...]
   or: or: littler [options]

Launches GNU R to execute the specified file containing R commands,
or takes commands from stdin using the specified options. This makes
it suitable to create  R scripts via the so-called shebang '#!/' line.

  -h, --help                 Give this help list
      --usage                Give a short usage message
  -V, --version              Print program version
      --vanilla              Pass the '--vanilla' option to R
      --slave                Pass the '--slave' option to R  
      --silent               Pass the '--silent' option to R  

Report bugs to <jeff.horner@@vanderbilt.edu> and
<dirk.eddelbuettel@@debian.org>.
@end example

@node Invoking littler, Problems, Sample, Top
@chapter Invoking @command{littler}
@cindex invoking
@cindex version
@cindex options
@cindex usage
@cindex help
@cindex getting help

The format for running the @command{littler} program is:

@example
littler @var{option} @dots{}
@end example

@code{littler} supports the following options:

@c Formatting copied from the Texinfo 4.0 manual.
@table @code
@item --help
@itemx -?
Print an informative help message describing the options and then exit
successfully.

@item --usage
Briefly list the options.

@item --version
@itemx -V
Print the version number of @command{littler} on the standard output
and then exit successfully.
@end table

@node Problems, Concept Index, Invoking littler, Top
@chapter Reporting Bugs
@cindex bugs
@cindex problems

If you find a bug in @command{littler}, please send electronic mail to
@email{jeff.horner@@vanderbilt.edu}.  Include the version number, which you can find by
running @w{@samp{littler --version}}.  Also include in your message the
output that the program produced and the output you expected.@refill

If you have other questions, comments or suggestions about
@command{littler}, contact the authors via electronic mail to
@email{jeff.horner@@vanderbilt.edu} or @email{edd@@debian.org}.  
The authors will try to help you out, although they
may not have time to fix your problems.

@node Copying, Overview, Instructions, Top
@include gpl.texinfo

@node Concept Index,  , Problems, Top
@unnumbered Concept Index

@cindex tail recursion
@printindex cp

@shortcontents
@contents
@bye
