
// Do not edit!  This file was autogenerated 
//      by ./bootstrap 
//      on Fri Oct  6 09:42:37 CDT 2006
//
// svnrevision and svndate are as reported by svn at that point in time,
// compiledate and compiletime are being filled gcc at compilation

#include <stdlib.h>
 
static const char* svnrevision = "92";
static const char* svndate = "2006-10-05 08:14:41";
static const char* compiletime = __TIME__;
static const char* compiledate = __DATE__;

