
// Do not edit!  This file was autogenerated 
//      by ./bootstrap 
//      on Thu Oct  5 08:09:07 CDT 2006
//
// svnrevision and svndate are as reported by svn at that point in time,
// compiledate and compiletime are being filled gcc at compilation

#include <stdlib.h>
 
static const char* svnrevision = "89";
static const char* svndate = "2006-10-03 11:47:37";
static const char* compiletime = __TIME__;
static const char* compiledate = __DATE__;

