
// Do not edit!  This file was autogenerated 
//      by ./bootstrap 
//      on Fri Oct  6 11:24:53 CDT 2006
//
// svnrevision and svndate are as reported by svn at that point in time,
// compiledate and compiletime are being filled gcc at compilation

#include <stdlib.h>
 
static const char* svnrevision = "95";
static const char* svndate = "2006-10-06 10:50:58";
static const char* compiletime = __TIME__;
static const char* compiledate = __DATE__;

