site_name: littler
site_url: https://github.com/eddelbuettel/littler
docs_dir: src
site_dir: docs
copyright: Copyright &copy; 2006 - present Dirk Eddelbuettel and Jeff Horner
repo_url: https://github.com/eddelbuettel/littler
edit_uri: ""

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.instant
  font:
    text: Lato
  favicon: assets/Rlogo.png
  logo: assets/Rlogo.svg

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eddelbuettel/littler
      name: littler on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/eddelbuettel
      name: eddelbuettel on Twitter

nav:
  - Home:
    - index.md
  - Reference:
    - man/littler.md
    - man/r.md
  - Articles:
    - Littler Examples: vignettes/littler-examples.md
    - Littler FAQ: vignettes/littler-faq.md
  - News:
    - news.md
  - Changelog:
    - changelog.md
