
// Do not edit!  This file was autogenerated 
//      by ./bootstrap 
//      on Wed Oct 14 13:16:27 CDT 2015
//
// gitrevision and gitdate are as reported by git at that point in time,
// compiledate and compiletime are being filled gcc at compilation

#include <stdlib.h>

static const char* gitrevision = "b4c97f3";
static const char* gitdate = "Fri Oct 2 08:36:28 2015 -0500";
#if defined(VERBOSE_BUILD)
    static const char* compiletime = __TIME__;
    static const char* compiledate = __DATE__;
#endif
